# Generated by Django 3.2.14 on 2022-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220803_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='weight',
            field=models.FloatField(default=10),
        ),
    ]
