# Generated by Django 3.2.14 on 2022-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_edge_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='(xxx) xxx-xxxx', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, default='pronouns', max_length=20, null=True),
        ),
    ]
