# Generated by Django 3.2.14 on 2022-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220803_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='weight',
            field=models.FloatField(default=100),
        ),
    ]
