# Generated by Django 3.2.14 on 2022-08-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='(xxx) xxx-xxxx\n(or easiest contact)', max_length=20, null=True),
        ),
    ]
