# Generated by Django 3.2.14 on 2022-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='(xxx) xxx-xxxx\n (or easiest contact)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, default='pronouns', max_length=30, null=True),
        ),
    ]
